services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15673:15672"
    networks:
      - micro-net

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - micro-net

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - micro-net

  auth-service:
    image: kousikdev/zcart-server-images:auth-1.0
    container_name: auth-service
    restart: always
    env_file: ./env/auth.env
    depends_on:
      - mongo
      - rabbitmq
      - redis
    ports:
      - "3000:3000"
    networks:
      - micro-net

  product-service:
    image: kousikdev/zcart-server-images:product-1.0
    container_name: product-service
    restart: always
    env_file: ./env/product.env
    depends_on:
      - mongo
      - rabbitmq
      - auth-service
    ports:
      - "3001:3001"
    networks:
      - micro-net

  cart-service:
    image: kousikdev/zcart-server-images:cart-1.0
    container_name: cart-service
    restart: always
    env_file: ./env/cart.env
    depends_on:
      - auth-service
      - product-service
    ports:
      - "3002:3002"
    networks:
      - micro-net

  order-service:
    image: kousikdev/zcart-server-images:order-1.0
    container_name: order-service
    restart: always
    env_file: ./env/order.env
    depends_on:
      - auth-service
      - product-service
      - cart-service
      - rabbitmq
    ports:
      - "3003:3003"
    networks:
      - micro-net

  payment-service:
    image: kousikdev/zcart-server-images:payment-1.0
    container_name: payment-service
    restart: always
    env_file: ./env/payment.env
    depends_on:
      - order-service
      - rabbitmq
    ports:
      - "3004:3004"
    networks:
      - micro-net

  notification-service:
    image: kousikdev/zcart-server-images:notification-1.1
    container_name: notification-service
    restart: always
    env_file: ./env/notification.env
    depends_on:
      - rabbitmq
      - order-service
      - payment-service
      - auth-service
      - product-service
      - cart-service
    ports:
      - "3005:3005"
    networks:
      - micro-net

  seller-service:
    image: kousikdev/zcart-server-images:seller-1.0
    container_name: seller-service
    restart: always
    env_file: ./env/seller.env
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3006:3006"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
